import {
  FireIcon,
  SkullIcon,
  FavouriteIcon,
  FlashIcon,
  VolumeHighIcon,
  MusicNote01Icon,
  Analytics01Icon,
  HeadphonesIcon,
  Moon02Icon,
  Add01Icon,
  Cancel01Icon,
  Alert01Icon,
  Time02Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  Radio01Icon,
  HourglassIcon,
} from 'hugeicons-react';

export {
  FireIcon,
  SkullIcon,
  FavouriteIcon as HeartIcon,
  FlashIcon as BoltIcon,
  VolumeHighIcon as SonarIcon,
  MusicNote01Icon as MusicIcon,
  Analytics01Icon as AnalyticsIcon,
  HeadphonesIcon,
  Moon02Icon as MoonIcon,
  Add01Icon as AddIcon,
  Cancel01Icon as CancelIcon,
  Alert01Icon as AlertIcon,
  Time02Icon as TimeIcon,
  ArrowLeft01Icon as ArrowLeftIcon,
  ArrowRight01Icon as ArrowRightIcon,
  Radio01Icon as RadioIcon,
  HourglassIcon,
};
